### ISSUE TITLE
abl_link: deken package misses Makefiles

### ISSUE THREAD

**Issue by umlaeute** [libpd/pd-for-ios#11]
thanks for sharing `[abl_link~]` via deken.

however the [deken-file](http://puredata.info/Members/ant1r/software/abl_link~/0.2/abl_link~-v0.2-%28Sources%29%28Linux-amd64-64%29-externals.tar.gz) lacks the Makefile to build the external.

please provide it in future uploads.

**Comment by nettoyeurny** [comment]
I'm a bit fuzzy on what goes into distributing sources via deken. Does this require any changes to files in this repo or is it just a matter of repackaging the source distribution? In any case, I'll close this issue here. Feel free to open a new issue against the new repo if there's anything I need to change on my side. (I'm not currently set up to upload anything to puredata.info, so it would be great if you would take care of that.)

**Comment by umlaeute** [comment]
a `(Sources)` deken-package should allow to (re)build the library (exactly), s oit should be self-contained.

basically this includes the sources and the build-system.

i would *not* include any third party libs (like `ableton_link`), but it would be good to include documentation on how to obtain (which version) of any 3rd party library. (my rule of thumb is: everything that is a `git-submodule` should not be included)

**Comment by nettoyeurny** [comment]
Of course, but my question was whether the missing Makefile was due to some issue with this repository (e.g., should the Makefile specify itself as a data file to be packaged for deken?) or is this just a matter of manually rebuilding the deken package to include the Makefile that doesn't require any changes to this repo?

**Comment by umlaeute** [comment]
since I do not know how you created the deken package, I have no clue why some files are missing from it.

**Comment by nettoyeurny** [comment]
The thing is, I didn't create the deken package myself. My question remains, though --- is there a preferred way to automate the creation of the source package (analogous to the way that pd-lib-builder stages binaries and help patches for deken), or is this orthogonal to the code in the abl_link repo? If it's the former, I'll be happy to make the necessary code changes.  If it's the latter, then this is the wrong place for this conversation and the way to resolve this is to just post a new source package.

**Comment by umlaeute** [comment]
i don't think that there is a preferred way to build the deken package.

Using the `deken` tool, it will (should) detect all the archs (including `Source`) but it will not ensure that the resulting package is usable in *any* way (including the possibility to *build*).

there's a [ticket for pd-lib-builder](https://github.com/pure-data/pd-lib-builder/issues/18) to add a `deken-source` target, but afaik it is not functional yet (at least it is not included in the current releases).

So you *could* add something to your repo to create a proper deken source package.
you could also decide not to.

I reported the issue here, because i haven't found a better place.
(after all, it was @nettoyeurny who announced the deken package on the Pd-list, making it kind of *official*, even though @Ant1r did the upload)

**Comment by nettoyeurny** [comment]
Thanks, @umlaeute ! @Ant1r graciously agreed to update the source package, so this issue will be taken care of soon.
