### ISSUE TITLE
abl_link: multiple objects share connection state

### ISSUE THREAD

**Issue by umlaeute** [libpd/pd-for-ios#13]
if i have multiple [abl_link~] objects in my running Pd instances, they all share the same connection state.
That is: if i `[connect 1(` one instance, the other instances will be connected to the global (networked) session as well.

also, multiple `[abl_link~]` objects in a single Pd instance are connected with each other, even if they are not connected with a global session.

**Comment by umlaeute** [comment]
both observations might be intentional.

if so, the documentation (help-patch) should make this explicit.

**Comment by nettoyeurny** [comment]
Yes, this is very much intentional; all instances of abl_link~ share the same Link instance under the hood. This agrees with the setup on iOS (where the ambient app manages the Link instance), and it seems like the right approach from a usability point of view (or else you'd be able to create patches that are out of sync with themselves).

Do you want to add a paragraph to the help patch and send me a pull request?

**Comment by umlaeute** [comment]
i'm currently swamped with things to do. if someone with a better understanding of the system were willing to do the chores, i'd :+1:

**Comment by nettoyeurny** [comment]
I just pushed a new help patch to the new abl_link repository, at https://github.com/libpd/abl_link.
